import type {KanaAlphabet, KanaColumn, KanaRow, KanaSet, KanaSymbol} from './types';

interface SymbolSeed {
    readonly symbol: string;
    readonly romaji: string;
    readonly row: KanaRow;
    readonly column: KanaColumn | null;
}

/** Русская транскрипция по ромадзи (приблизительное произношение). */
const RU_BY_ROMAJI: Record<string, string> = {
    // Гласные
    a: 'а',
    i: 'и',
    u: 'у',
    e: 'э',
    o: 'о',
    // K / S / T / N
    ka: 'ка',
    ki: 'ки',
    ku: 'ку',
    ke: 'кэ',
    ko: 'ко',
    sa: 'са',
    shi: 'си',
    su: 'су',
    se: 'сэ',
    so: 'со',
    ta: 'та',
    chi: 'чи',
    tsu: 'цу',
    te: 'тэ',
    to: 'то',
    na: 'на',
    ni: 'ни',
    nu: 'ну',
    ne: 'нэ',
    no: 'но',
    // H / M / Y / R / W
    ha: 'ха',
    hi: 'хи',
    fu: 'фу',
    he: 'хэ',
    ho: 'хо',
    ma: 'ма',
    mi: 'ми',
    mu: 'му',
    me: 'мэ',
    mo: 'мо',
    ya: 'я',
    yu: 'ю',
    yo: 'ё',
    ra: 'ра',
    ri: 'ри',
    ru: 'ру',
    re: 'рэ',
    ro: 'ро',
    wa: 'ва',
    wo: 'во',
    n: 'н',
    // Дакуон / хандакуон
    ga: 'га',
    gi: 'ги',
    gu: 'гу',
    ge: 'гэ',
    go: 'го',
    za: 'дза',
    ji: 'дзи',
    zu: 'дзу',
    ze: 'дзэ',
    zo: 'дзо',
    da: 'да',
    de: 'дэ',
    do: 'до',
    ba: 'ба',
    bi: 'би',
    bu: 'бу',
    be: 'бэ',
    bo: 'бо',
    pa: 'па',
    pi: 'пи',
    pu: 'пу',
    pe: 'пэ',
    po: 'по',
    // Ёон
    kya: 'кя',
    kyu: 'кю',
    kyo: 'кё',
    sha: 'ся',
    shu: 'сю',
    sho: 'сё',
    cha: 'тя',
    chu: 'тю',
    cho: 'тё',
    nya: 'ня',
    nyu: 'ню',
    nyo: 'нё',
    hya: 'хя',
    hyu: 'хю',
    hyo: 'хё',
    mya: 'мя',
    myu: 'мю',
    myo: 'мё',
    rya: 'ря',
    ryu: 'рю',
    ryo: 'рё',
    gya: 'гя',
    gyu: 'гю',
    gyo: 'гё',
    ja: 'дзя',
    ju: 'дзю',
    jo: 'дзё',
    bya: 'бя',
    byu: 'бю',
    byo: 'бё',
    pya: 'пя',
    pyu: 'пю',
    pyo: 'пё',
};

/** Возвращает русскую транскрипцию по ромадзи (с безопасным запасным вариантом). */
function ruForRomaji(romaji: string): string {
    return RU_BY_ROMAJI[romaji] ?? romaji;
}

/** Порождает массив знаков одного набора одной азбуки. */
function buildSet(
    alphabet: KanaAlphabet,
    set: KanaSet,
    seeds: readonly SymbolSeed[],
): readonly KanaSymbol[] {
    return seeds.map((seed) => ({
        id: `${alphabet}_${set}_${seed.symbol}`,
        symbol: seed.symbol,
        romaji: seed.romaji,
        ru: ruForRomaji(seed.romaji),
        alphabet,
        set,
        row: seed.row,
        column: seed.column,
    }));
}

// ============================================================================
// Хирагана
// ============================================================================

const HIRAGANA_BASE_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'あ', romaji: 'a', row: 'vowels', column: 'a'},
    {symbol: 'い', romaji: 'i', row: 'vowels', column: 'i'},
    {symbol: 'う', romaji: 'u', row: 'vowels', column: 'u'},
    {symbol: 'え', romaji: 'e', row: 'vowels', column: 'e'},
    {symbol: 'お', romaji: 'o', row: 'vowels', column: 'o'},
    {symbol: 'か', romaji: 'ka', row: 'k', column: 'a'},
    {symbol: 'き', romaji: 'ki', row: 'k', column: 'i'},
    {symbol: 'く', romaji: 'ku', row: 'k', column: 'u'},
    {symbol: 'け', romaji: 'ke', row: 'k', column: 'e'},
    {symbol: 'こ', romaji: 'ko', row: 'k', column: 'o'},
    {symbol: 'さ', romaji: 'sa', row: 's', column: 'a'},
    {symbol: 'し', romaji: 'shi', row: 's', column: 'i'},
    {symbol: 'す', romaji: 'su', row: 's', column: 'u'},
    {symbol: 'せ', romaji: 'se', row: 's', column: 'e'},
    {symbol: 'そ', romaji: 'so', row: 's', column: 'o'},
    {symbol: 'た', romaji: 'ta', row: 't', column: 'a'},
    {symbol: 'ち', romaji: 'chi', row: 't', column: 'i'},
    {symbol: 'つ', romaji: 'tsu', row: 't', column: 'u'},
    {symbol: 'て', romaji: 'te', row: 't', column: 'e'},
    {symbol: 'と', romaji: 'to', row: 't', column: 'o'},
    {symbol: 'な', romaji: 'na', row: 'n', column: 'a'},
    {symbol: 'に', romaji: 'ni', row: 'n', column: 'i'},
    {symbol: 'ぬ', romaji: 'nu', row: 'n', column: 'u'},
    {symbol: 'ね', romaji: 'ne', row: 'n', column: 'e'},
    {symbol: 'の', romaji: 'no', row: 'n', column: 'o'},
    {symbol: 'は', romaji: 'ha', row: 'h', column: 'a'},
    {symbol: 'ひ', romaji: 'hi', row: 'h', column: 'i'},
    {symbol: 'ふ', romaji: 'fu', row: 'h', column: 'u'},
    {symbol: 'へ', romaji: 'he', row: 'h', column: 'e'},
    {symbol: 'ほ', romaji: 'ho', row: 'h', column: 'o'},
    {symbol: 'ま', romaji: 'ma', row: 'm', column: 'a'},
    {symbol: 'み', romaji: 'mi', row: 'm', column: 'i'},
    {symbol: 'む', romaji: 'mu', row: 'm', column: 'u'},
    {symbol: 'め', romaji: 'me', row: 'm', column: 'e'},
    {symbol: 'も', romaji: 'mo', row: 'm', column: 'o'},
    {symbol: 'や', romaji: 'ya', row: 'y', column: 'a'},
    {symbol: 'ゆ', romaji: 'yu', row: 'y', column: 'u'},
    {symbol: 'よ', romaji: 'yo', row: 'y', column: 'o'},
    {symbol: 'ら', romaji: 'ra', row: 'r', column: 'a'},
    {symbol: 'り', romaji: 'ri', row: 'r', column: 'i'},
    {symbol: 'る', romaji: 'ru', row: 'r', column: 'u'},
    {symbol: 'れ', romaji: 're', row: 'r', column: 'e'},
    {symbol: 'ろ', romaji: 'ro', row: 'r', column: 'o'},
    {symbol: 'わ', romaji: 'wa', row: 'w', column: 'a'},
    {symbol: 'を', romaji: 'wo', row: 'w', column: 'o'},
    {symbol: 'ん', romaji: 'n', row: 'w', column: null},
];

const HIRAGANA_DAKUON_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'が', romaji: 'ga', row: 'g', column: 'a'},
    {symbol: 'ぎ', romaji: 'gi', row: 'g', column: 'i'},
    {symbol: 'ぐ', romaji: 'gu', row: 'g', column: 'u'},
    {symbol: 'げ', romaji: 'ge', row: 'g', column: 'e'},
    {symbol: 'ご', romaji: 'go', row: 'g', column: 'o'},
    {symbol: 'ざ', romaji: 'za', row: 'z', column: 'a'},
    {symbol: 'じ', romaji: 'ji', row: 'z', column: 'i'},
    {symbol: 'ず', romaji: 'zu', row: 'z', column: 'u'},
    {symbol: 'ぜ', romaji: 'ze', row: 'z', column: 'e'},
    {symbol: 'ぞ', romaji: 'zo', row: 'z', column: 'o'},
    {symbol: 'だ', romaji: 'da', row: 'd', column: 'a'},
    {symbol: 'ぢ', romaji: 'ji', row: 'd', column: 'i'},
    {symbol: 'づ', romaji: 'zu', row: 'd', column: 'u'},
    {symbol: 'で', romaji: 'de', row: 'd', column: 'e'},
    {symbol: 'ど', romaji: 'do', row: 'd', column: 'o'},
    {symbol: 'ば', romaji: 'ba', row: 'b', column: 'a'},
    {symbol: 'び', romaji: 'bi', row: 'b', column: 'i'},
    {symbol: 'ぶ', romaji: 'bu', row: 'b', column: 'u'},
    {symbol: 'べ', romaji: 'be', row: 'b', column: 'e'},
    {symbol: 'ぼ', romaji: 'bo', row: 'b', column: 'o'},
    {symbol: 'ぱ', romaji: 'pa', row: 'p', column: 'a'},
    {symbol: 'ぴ', romaji: 'pi', row: 'p', column: 'i'},
    {symbol: 'ぷ', romaji: 'pu', row: 'p', column: 'u'},
    {symbol: 'ぺ', romaji: 'pe', row: 'p', column: 'e'},
    {symbol: 'ぽ', romaji: 'po', row: 'p', column: 'o'},
];

const HIRAGANA_YOON_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'きゃ', romaji: 'kya', row: 'ky', column: 'a'},
    {symbol: 'きゅ', romaji: 'kyu', row: 'ky', column: 'u'},
    {symbol: 'きょ', romaji: 'kyo', row: 'ky', column: 'o'},
    {symbol: 'しゃ', romaji: 'sha', row: 'sh', column: 'a'},
    {symbol: 'しゅ', romaji: 'shu', row: 'sh', column: 'u'},
    {symbol: 'しょ', romaji: 'sho', row: 'sh', column: 'o'},
    {symbol: 'ちゃ', romaji: 'cha', row: 'ch', column: 'a'},
    {symbol: 'ちゅ', romaji: 'chu', row: 'ch', column: 'u'},
    {symbol: 'ちょ', romaji: 'cho', row: 'ch', column: 'o'},
    {symbol: 'にゃ', romaji: 'nya', row: 'ny', column: 'a'},
    {symbol: 'にゅ', romaji: 'nyu', row: 'ny', column: 'u'},
    {symbol: 'にょ', romaji: 'nyo', row: 'ny', column: 'o'},
    {symbol: 'ひゃ', romaji: 'hya', row: 'hy', column: 'a'},
    {symbol: 'ひゅ', romaji: 'hyu', row: 'hy', column: 'u'},
    {symbol: 'ひょ', romaji: 'hyo', row: 'hy', column: 'o'},
    {symbol: 'みゃ', romaji: 'mya', row: 'my', column: 'a'},
    {symbol: 'みゅ', romaji: 'myu', row: 'my', column: 'u'},
    {symbol: 'みょ', romaji: 'myo', row: 'my', column: 'o'},
    {symbol: 'りゃ', romaji: 'rya', row: 'ry', column: 'a'},
    {symbol: 'りゅ', romaji: 'ryu', row: 'ry', column: 'u'},
    {symbol: 'りょ', romaji: 'ryo', row: 'ry', column: 'o'},
    {symbol: 'ぎゃ', romaji: 'gya', row: 'gy', column: 'a'},
    {symbol: 'ぎゅ', romaji: 'gyu', row: 'gy', column: 'u'},
    {symbol: 'ぎょ', romaji: 'gyo', row: 'gy', column: 'o'},
    {symbol: 'じゃ', romaji: 'ja', row: 'j', column: 'a'},
    {symbol: 'じゅ', romaji: 'ju', row: 'j', column: 'u'},
    {symbol: 'じょ', romaji: 'jo', row: 'j', column: 'o'},
    {symbol: 'びゃ', romaji: 'bya', row: 'by', column: 'a'},
    {symbol: 'びゅ', romaji: 'byu', row: 'by', column: 'u'},
    {symbol: 'びょ', romaji: 'byo', row: 'by', column: 'o'},
    {symbol: 'ぴゃ', romaji: 'pya', row: 'py', column: 'a'},
    {symbol: 'ぴゅ', romaji: 'pyu', row: 'py', column: 'u'},
    {symbol: 'ぴょ', romaji: 'pyo', row: 'py', column: 'o'},
];

// ============================================================================
// Катакана
// ============================================================================

const KATAKANA_BASE_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'ア', romaji: 'a', row: 'vowels', column: 'a'},
    {symbol: 'イ', romaji: 'i', row: 'vowels', column: 'i'},
    {symbol: 'ウ', romaji: 'u', row: 'vowels', column: 'u'},
    {symbol: 'エ', romaji: 'e', row: 'vowels', column: 'e'},
    {symbol: 'オ', romaji: 'o', row: 'vowels', column: 'o'},
    {symbol: 'カ', romaji: 'ka', row: 'k', column: 'a'},
    {symbol: 'キ', romaji: 'ki', row: 'k', column: 'i'},
    {symbol: 'ク', romaji: 'ku', row: 'k', column: 'u'},
    {symbol: 'ケ', romaji: 'ke', row: 'k', column: 'e'},
    {symbol: 'コ', romaji: 'ko', row: 'k', column: 'o'},
    {symbol: 'サ', romaji: 'sa', row: 's', column: 'a'},
    {symbol: 'シ', romaji: 'shi', row: 's', column: 'i'},
    {symbol: 'ス', romaji: 'su', row: 's', column: 'u'},
    {symbol: 'セ', romaji: 'se', row: 's', column: 'e'},
    {symbol: 'ソ', romaji: 'so', row: 's', column: 'o'},
    {symbol: 'タ', romaji: 'ta', row: 't', column: 'a'},
    {symbol: 'チ', romaji: 'chi', row: 't', column: 'i'},
    {symbol: 'ツ', romaji: 'tsu', row: 't', column: 'u'},
    {symbol: 'テ', romaji: 'te', row: 't', column: 'e'},
    {symbol: 'ト', romaji: 'to', row: 't', column: 'o'},
    {symbol: 'ナ', romaji: 'na', row: 'n', column: 'a'},
    {symbol: 'ニ', romaji: 'ni', row: 'n', column: 'i'},
    {symbol: 'ヌ', romaji: 'nu', row: 'n', column: 'u'},
    {symbol: 'ネ', romaji: 'ne', row: 'n', column: 'e'},
    {symbol: 'ノ', romaji: 'no', row: 'n', column: 'o'},
    {symbol: 'ハ', romaji: 'ha', row: 'h', column: 'a'},
    {symbol: 'ヒ', romaji: 'hi', row: 'h', column: 'i'},
    {symbol: 'フ', romaji: 'fu', row: 'h', column: 'u'},
    {symbol: 'ヘ', romaji: 'he', row: 'h', column: 'e'},
    {symbol: 'ホ', romaji: 'ho', row: 'h', column: 'o'},
    {symbol: 'マ', romaji: 'ma', row: 'm', column: 'a'},
    {symbol: 'ミ', romaji: 'mi', row: 'm', column: 'i'},
    {symbol: 'ム', romaji: 'mu', row: 'm', column: 'u'},
    {symbol: 'メ', romaji: 'me', row: 'm', column: 'e'},
    {symbol: 'モ', romaji: 'mo', row: 'm', column: 'o'},
    {symbol: 'ヤ', romaji: 'ya', row: 'y', column: 'a'},
    {symbol: 'ユ', romaji: 'yu', row: 'y', column: 'u'},
    {symbol: 'ヨ', romaji: 'yo', row: 'y', column: 'o'},
    {symbol: 'ラ', romaji: 'ra', row: 'r', column: 'a'},
    {symbol: 'リ', romaji: 'ri', row: 'r', column: 'i'},
    {symbol: 'ル', romaji: 'ru', row: 'r', column: 'u'},
    {symbol: 'レ', romaji: 're', row: 'r', column: 'e'},
    {symbol: 'ロ', romaji: 'ro', row: 'r', column: 'o'},
    {symbol: 'ワ', romaji: 'wa', row: 'w', column: 'a'},
    {symbol: 'ヲ', romaji: 'wo', row: 'w', column: 'o'},
    {symbol: 'ン', romaji: 'n', row: 'w', column: null},
];

const KATAKANA_DAKUON_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'ガ', romaji: 'ga', row: 'g', column: 'a'},
    {symbol: 'ギ', romaji: 'gi', row: 'g', column: 'i'},
    {symbol: 'グ', romaji: 'gu', row: 'g', column: 'u'},
    {symbol: 'ゲ', romaji: 'ge', row: 'g', column: 'e'},
    {symbol: 'ゴ', romaji: 'go', row: 'g', column: 'o'},
    {symbol: 'ザ', romaji: 'za', row: 'z', column: 'a'},
    {symbol: 'ジ', romaji: 'ji', row: 'z', column: 'i'},
    {symbol: 'ズ', romaji: 'zu', row: 'z', column: 'u'},
    {symbol: 'ゼ', romaji: 'ze', row: 'z', column: 'e'},
    {symbol: 'ゾ', romaji: 'zo', row: 'z', column: 'o'},
    {symbol: 'ダ', romaji: 'da', row: 'd', column: 'a'},
    {symbol: 'ヂ', romaji: 'ji', row: 'd', column: 'i'},
    {symbol: 'ヅ', romaji: 'zu', row: 'd', column: 'u'},
    {symbol: 'デ', romaji: 'de', row: 'd', column: 'e'},
    {symbol: 'ド', romaji: 'do', row: 'd', column: 'o'},
    {symbol: 'バ', romaji: 'ba', row: 'b', column: 'a'},
    {symbol: 'ビ', romaji: 'bi', row: 'b', column: 'i'},
    {symbol: 'ブ', romaji: 'bu', row: 'b', column: 'u'},
    {symbol: 'ベ', romaji: 'be', row: 'b', column: 'e'},
    {symbol: 'ボ', romaji: 'bo', row: 'b', column: 'o'},
    {symbol: 'パ', romaji: 'pa', row: 'p', column: 'a'},
    {symbol: 'ピ', romaji: 'pi', row: 'p', column: 'i'},
    {symbol: 'プ', romaji: 'pu', row: 'p', column: 'u'},
    {symbol: 'ペ', romaji: 'pe', row: 'p', column: 'e'},
    {symbol: 'ポ', romaji: 'po', row: 'p', column: 'o'},
];

const KATAKANA_YOON_SEEDS: readonly SymbolSeed[] = [
    {symbol: 'キャ', romaji: 'kya', row: 'ky', column: 'a'},
    {symbol: 'キュ', romaji: 'kyu', row: 'ky', column: 'u'},
    {symbol: 'キョ', romaji: 'kyo', row: 'ky', column: 'o'},
    {symbol: 'シャ', romaji: 'sha', row: 'sh', column: 'a'},
    {symbol: 'シュ', romaji: 'shu', row: 'sh', column: 'u'},
    {symbol: 'ショ', romaji: 'sho', row: 'sh', column: 'o'},
    {symbol: 'チャ', romaji: 'cha', row: 'ch', column: 'a'},
    {symbol: 'チュ', romaji: 'chu', row: 'ch', column: 'u'},
    {symbol: 'チョ', romaji: 'cho', row: 'ch', column: 'o'},
    {symbol: 'ニャ', romaji: 'nya', row: 'ny', column: 'a'},
    {symbol: 'ニュ', romaji: 'nyu', row: 'ny', column: 'u'},
    {symbol: 'ニョ', romaji: 'nyo', row: 'ny', column: 'o'},
    {symbol: 'ヒャ', romaji: 'hya', row: 'hy', column: 'a'},
    {symbol: 'ヒュ', romaji: 'hyu', row: 'hy', column: 'u'},
    {symbol: 'ヒョ', romaji: 'hyo', row: 'hy', column: 'o'},
    {symbol: 'ミャ', romaji: 'mya', row: 'my', column: 'a'},
    {symbol: 'ミュ', romaji: 'myu', row: 'my', column: 'u'},
    {symbol: 'ミョ', romaji: 'myo', row: 'my', column: 'o'},
    {symbol: 'リャ', romaji: 'rya', row: 'ry', column: 'a'},
    {symbol: 'リュ', romaji: 'ryu', row: 'ry', column: 'u'},
    {symbol: 'リョ', romaji: 'ryo', row: 'ry', column: 'o'},
    {symbol: 'ギャ', romaji: 'gya', row: 'gy', column: 'a'},
    {symbol: 'ギュ', romaji: 'gyu', row: 'gy', column: 'u'},
    {symbol: 'ギョ', romaji: 'gyo', row: 'gy', column: 'o'},
    {symbol: 'ジャ', romaji: 'ja', row: 'j', column: 'a'},
    {symbol: 'ジュ', romaji: 'ju', row: 'j', column: 'u'},
    {symbol: 'ジョ', romaji: 'jo', row: 'j', column: 'o'},
    {symbol: 'ビャ', romaji: 'bya', row: 'by', column: 'a'},
    {symbol: 'ビュ', romaji: 'byu', row: 'by', column: 'u'},
    {symbol: 'ビョ', romaji: 'byo', row: 'by', column: 'o'},
    {symbol: 'ピャ', romaji: 'pya', row: 'py', column: 'a'},
    {symbol: 'ピュ', romaji: 'pyu', row: 'py', column: 'u'},
    {symbol: 'ピョ', romaji: 'pyo', row: 'py', column: 'o'},
];

// ============================================================================
// Сборка и публикация
// ============================================================================

export const HIRAGANA_BASE: readonly KanaSymbol[] = buildSet('hiragana', 'base', HIRAGANA_BASE_SEEDS);
export const HIRAGANA_DAKUON: readonly KanaSymbol[] = buildSet('hiragana', 'dakuon', HIRAGANA_DAKUON_SEEDS);
export const HIRAGANA_YOON: readonly KanaSymbol[] = buildSet('hiragana', 'yoon', HIRAGANA_YOON_SEEDS);
export const KATAKANA_BASE: readonly KanaSymbol[] = buildSet('katakana', 'base', KATAKANA_BASE_SEEDS);
export const KATAKANA_DAKUON: readonly KanaSymbol[] = buildSet('katakana', 'dakuon', KATAKANA_DAKUON_SEEDS);
export const KATAKANA_YOON: readonly KanaSymbol[] = buildSet('katakana', 'yoon', KATAKANA_YOON_SEEDS);

/** Каталог знаков по азбуке и набору. */
export const KANA_CATALOG: Record<KanaAlphabet, Record<KanaSet, readonly KanaSymbol[]>> = {
    hiragana: {base: HIRAGANA_BASE, dakuon: HIRAGANA_DAKUON, yoon: HIRAGANA_YOON},
    katakana: {base: KATAKANA_BASE, dakuon: KATAKANA_DAKUON, yoon: KATAKANA_YOON},
};

/** Плоский список всех знаков всех азбук и наборов. */
export const ALL_KANA: readonly KanaSymbol[] = [
    ...HIRAGANA_BASE,
    ...HIRAGANA_DAKUON,
    ...HIRAGANA_YOON,
    ...KATAKANA_BASE,
    ...KATAKANA_DAKUON,
    ...KATAKANA_YOON,
];